# This Makefile maintains a repository of allocation site
# metadata, shadowing libraries and executables in the system,
# similar to the /usr/lib/debug hierarchy. 

# HACK! for spaces
nullstring :=
space := $(nullstring) # end

THIS_MAKEFILE := $(realpath $(lastword $(MAKEFILE_LIST)))
LIBALLOCS ?= $(realpath $(dir $(THIS_MAKEFILE))/..)
LIBRUNT ?= $(realpath $(dir $(THIS_MAKEFILE))/../contrib/libsystrap/librunt)
LIBALLOCSTOOL ?= $(realpath $(dir $(THIS_MAKEFILE))/../contrib/liballocstool)

META_BASE ?= /usr/lib/meta
$(warning META_BASE is $(META_BASE))

DWARFTYPES ?= $(dir $(THIS_MAKEFILE))/dwarftypes
FRAMETYPES ?= $(dir $(THIS_MAKEFILE))/frametypes
ALLOCSITES ?= $(dir $(THIS_MAKEFILE))/allocsites
ALLOCSITES_BLOOM ?= $(dir $(THIS_MAKEFILE))/allocsites-bloom
ALLOCTYPES ?= $(dir $(THIS_MAKEFILE))/alloctypes
METAVECTOR ?= $(dir $(THIS_MAKEFILE))/metavector

LDD_FUNCS ?= $(dir $(THIS_MAKEFILE))/ldd-funcs.sh
OBJDUMPALLOCS ?= $(dir $(THIS_MAKEFILE))/objdumpallocs
MERGE_ALLOCS ?= $(dir $(THIS_MAKEFILE))/merge-allocs.sh
GATHER_SRCALLOCS ?= $(dir $(THIS_MAKEFILE))/gather-srcallocs.sh

OBJDUMPMEMACC ?= $(dir $(THIS_MAKEFILE))/objdumpmemacc
MERGE_MEMACC ?= $(dir $(THIS_MAKEFILE))/merge-allocs.sh # FIXME: change name
GATHER_SRCMEMACC ?= $(dir $(THIS_MAKEFILE))/gather-srcmemacc.sh

CFLAGS += -I$(LIBALLOCSTOOL)/include -I$(LIBALLOCS)/include -I$(LIBRUNT)/include

META_CC ?= $(CC)
META_CFLAGS ?= $(CFLAGS)

# By default, remake everything we have already made,
# but don't make new .allocsites files.
default: $(shell find $(META_BASE) -type f -name '*.allocsites*' ! -name 'Makefile.meta' )

# Remaking a .allocsites file from the analogous file 
# in the system.
prefix_exactly_one_slash = $(shell echo "$1" | sed 's|^/*\(.*\)|/\1|' )
$(META_BASE)/%.objallocs: $(call prefix_exactly_one_slash,%)
	mkdir -p $$(dirname "$@")
	$(OBJDUMPALLOCS) "$<" | sed "s|.*|$<\t&|" > "$@" || (rm -f "$@"; false)
$(META_BASE)/%.objmemacc: $(call prefix_exactly_one_slash,%)
	mkdir -p $$(dirname "$@")
	$(OBJDUMPMEMACC) "$<" | sed "s|.*|$<\t&|" > "$@" || (rm -f "$@"; false)

# We also know how to build a lib%-uniqtypes.so for each executable.
# Which allocsites files does an executable's uniqtypes depend on?
# depend = $(shell $(OBJDEPS) "$1" 2>/dev/null | cut -f1 | while read line; do readlink -f "$$line"; done )

# # Note that $1 is always '/'-prefixed here, so we don't insert another L-- here
# # allocsites_from_obj = $(patsubst %,$(META_BASE)%.allocsites,$1)
# # all_allocsites_for_obj = $(foreach f,$1 $(call depend,$1),$(call allocsites_from_obj,$(f)))

# don't build /usr/lib/meta/usr/lib/meta/anything... 
# and it's a bug if we try
$(META_BASE)$(META_BASE)/%:
	false

$(META_BASE)/%.srcallocs: $(META_BASE)/%.objallocs
	( $(GATHER_SRCALLOCS) "$<" 2>&1 1>"$@" || (rm -f "$@"; false) ) | tee "$@.rej"
	test -e "$@"

$(META_BASE)/%.allocs: $(META_BASE)/%.objallocs $(META_BASE)/%.srcallocs
	( $(MERGE_ALLOCS) $+ 2>&1 1>"$@" || (rm -f "$@"; false) ) | tee "$@.rej"
	test -e "$@"

$(META_BASE)/%.srcmemacc: $(META_BASE)/%.objmemacc
	( $(GATHER_SRCMEMACC) "$<" 2>&1 1>"$@" || (rm -f "$@"; false) ) | tee "$@.rej"
	test -e "$@"

$(META_BASE)/%.memacc: $(META_BASE)/%.objmemacc $(META_BASE)/%.srcmemacc
	( $(MERGE_MEMACC) $+ 2>&1 1>"$@" || (rm -f "$@"; false) ) | tee "$@.rej"
	test -e "$@"

METADATA_KINDS ?= roottypes dwarftypes alloctypes frametypes allocsites extrasyms metavector \
  # starts-bitmaps allocsites-bloom 
# can't use builtin .o rule in case CC is not gcc (section flags injection attack
# using "... comdat# ..." doesn't work except on gcc). (FIXME: use configure-time
# adaptation found in glibc's libc-symbols.h?)

meta_sources =
# It's not the existence of a file that we care about; it's the inclusion
# of a file in the link. But it's OK -- make let us incrementally build
# the list of inputs across a series of rules.
ifneq ($(filter dwarftypes,$(METADATA_KINDS)),)
$(info Generating dwarftypes)
meta_sources += $(META_BASE)/$(1)-roottypes.c $(META_BASE)/$(1)-dwarftypes.c
endif
ifneq ($(filter alloctypes,$(METADATA_KINDS)),)
$(info Generating alloctypes)
meta_sources += $(META_BASE)/$(1)-alloctypes.c
endif
ifneq ($(filter allocsites,$(METADATA_KINDS)),)
$(info Generating allocsites)
meta_sources += $(META_BASE)/$(1)-allocsites.c
endif
ifneq ($(filter metavector,$(METADATA_KINDS)),)
$(info Generating metavector)
meta_sources += $(META_BASE)/$(1)-metavector.c
endif
ifneq ($(filter allocsites-bloom,$(METADATA_KINDS)),)
$(info Generating allocsites-bloom)
meta_sources += $(META_BASE)/$(1)-allocsites-bloom.c
endif
ifneq ($(filter frametypes,$(METADATA_KINDS)),)
$(info Generating frametypes)
meta_sources += $(META_BASE)/$(1)-frametypes.c
endif

# for debugging, try: @echo all dependencies: $+
$(META_BASE)/%-meta.so: /% $(call meta_sources,%)
	$(META_CC) $(META_CFLAGS) -shared -Wl,--hash-style=both -o "$@" $(filter %.c,$+)

SWAP_STDOUT_STDERR := 3>&2 2>&1 1>&3

# We have a new taxonomy of meta-information, as follows.
# uniqtypes that we always generate (void, existential...)
.PRECIOUS: $(META_BASE)/%-roottypes.c
$(META_BASE)/%-roottypes.c: $(dir $(THIS_MAKEFILE))/roottypes.c
	mkdir -p $(dir $@)
	cp $(dir $(THIS_MAKEFILE))/roottypes.c $@
# real uniqtypes
.PRECIOUS: $(META_BASE)/%-dwarftypes.c
$(META_BASE)/%-dwarftypes.c: /%
	mkdir -p $(dir $@)
	errs=$$( ( $(DWARFTYPES) $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# synthetic heap uniqtypes: depends on real uniqtypes
.PRECIOUS: $(META_BASE)/%-alloctypes.c
$(META_BASE)/%-alloctypes.c: /% $(META_BASE)/%.allocs
	mkdir -p $(dir $@)
	errs=$$( ( $(ALLOCTYPES) $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# frame uniqtypes: depends on real uniqtypes
.PRECIOUS: $(META_BASE)/%-frametypes.c
$(META_BASE)/%-frametypes.c: /%
	mkdir -p $(dir $@)
	errs=$$( ( $(FRAMETYPES) $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# heap allocsites: depends on synthetic heap types
.PRECIOUS: $(META_BASE)/%-allocsites.c
$(META_BASE)/%-allocsites.c: $(META_BASE)/%.allocs
	mkdir -p $(dir $@)
	errs=$$( ( $(ALLOCSITES) < $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# heap allocsites bloom filter: depends on heap allocsites
.PRECIOUS: $(META_BASE)/%-allocsites-bloom.c
$(META_BASE)/%-allocsites-bloom.c: $(META_BASE)/%.allocs
	mkdir -p $(dir $@)
	errs=$$( ( $(ALLOCSITES_BLOOM) < $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# file extrasyms: does *not* depend on anything (just generates fake syms from debug info)
.PRECIOUS: $(META_BASE)/%-extrasyms.c
$(META_BASE)/%-extrasyms.c: /%
	mkdir -p $(dir $@)
	errs=$$( ( $(EXTRASYMS) $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# file sorted meta-vector: type info is optional -- we might want to use this from librunt
# -- so just emit weak references to the types? and/or use conditional compilation?
# file per-segment starts bitmaps are now included here
# file sorted meta-vector really with type info: depends on real uniqtypes
.PRECIOUS: $(META_BASE)/%-metavector.c
$(META_BASE)/%-metavector.c: /%
	mkdir -p $(dir $@)
	errs=$$( ( $(METAVECTOR) $< $(SWAP_STDOUT_STDERR) ) 2>$@ ); \
	status=$$?; echo "$$errs" | gzip >$@.log.gz; [ $$status -eq 0 ] || (mv $@ $@.err; false)
# Given this complexity, perhaps we should
# 1. never output struct definitions in-line. always include them from a header.
#     -- the header can use #ifdef-guards to make repeated includes harmless
# 2. try to save running time / code by making multiple kinds of metadata
#     generable from a single tool invocation?
#    - e.g.  build a single program with command-line options --types --synthetic-heap --frame --heap-alloc-sites --heap-alloc-bloom --file-extrasyms --file-meta-vector --file-starts-bitmaps
#    - allow it to be $0-symlinked as tools which simply generate a single kind of meta-info
